---
- name: Converge
  hosts: localhost
  gather_facts: false
  roles:
    - role: padmini.k8s_cilium_centos
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"
