#SPDX-License-Identifier: MIT-0
---
# handlers file for k8s_cilium_centos
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart crio
  ansible.builtin.systemd:
    name: crio
    state: restarted
    enabled: yes

- name: restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    enabled: yes
