---
- name: Install Cilium CNI using Helm
  hosts: all
  become: true

  vars:
    cilium_version: "1.18.1"
    cilium_namespace: "kube-system"
    kubeconfig_path: "/etc/kubernetes/admin.conf"
    cilium_values_file: "./cilium-values.yml"

  tasks:

    - name: Add Helm repo
      ansible.builtin.shell: |
        curl https://baltocdn.com/helm/signing.asc | sudo tee /etc/pki/rpm-gpg/helm.asc
        cat <<EOF | sudo tee /etc/yum.repos.d/helm.repo
        [helm]
        name=Helm
        baseurl=https://baltocdn.com/helm/stable/rpm
        enabled=1
        gpgcheck=1
        gpgkey=file:///etc/pki/rpm-gpg/helm.asc
        EOF
      args:
        creates: /etc/yum.repos.d/helm.repo

    - name: Install Helm
      ansible.builtin.package:
        name: helm
        state: present
      ignore_errors: true

    - name: Ensure Helm is installed
      ansible.builtin.command: helm version --short
      register: helm_check
      changed_when: false
      failed_when: helm_check.rc != 0
      tags: always


    - name: Ensure Cilium Helm repo is added
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io
      register: helm_repo_result
      failed_when: >
        helm_repo_result.failed and
        ("already have a repository named" not in helm_repo_result.msg)
      tags: helm

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update
      changed_when: false
      tags: helm

    - name: Install or upgrade Cilium using Helm
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        release_namespace: "{{ cilium_namespace }}"
        create_namespace: true
        values_files:
          - "{{ cilium_values_file }}"
        chart_version: "{{ cilium_version }}"
        kubeconfig: "{{ kubeconfig_path }}"
        wait: true
      tags: cilium

    - name: Wait for Cilium pods to be ready
      ansible.builtin.shell: |
        kubectl get pods -n {{ cilium_namespace }} -l k8s-app=cilium \
        -o jsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -q 'false' && exit 1 || exit 0
      register: cilium_readiness
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      retries: 10
      delay: 15
      until: cilium_readiness.rc == 0
      changed_when: false
      tags: cilium
