---
- name: Install Cilium CNI using Helm
  hosts: localhost
  become: true

  vars:
    # Helm chart version (NOT app version). Check: helm search repo cilium --versions
    cilium_chart_version: "1.18.1"
    cilium_namespace: "kube-system"
    kubeconfig_path: "/etc/kubernetes/admin.conf"
    cilium_values_file: "./cilium-values.yml"

  tasks:
    - name: Ensure dependencies are present
      ansible.builtin.package:
        name:
          - curl
        state: present

    - name: Install Helm if not present
      ansible.builtin.shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Ensure Cilium Helm repo is added
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update
      changed_when: false

    - name: Install or upgrade Cilium using Helm
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        chart_version: "{{ cilium_chart_version }}"
        release_namespace: "{{ cilium_namespace }}"
        create_namespace: true
        values_files:
          - "{{ cilium_values_file }}"
        kubeconfig: "{{ kubeconfig_path }}"
        wait: true

    - name: Wait for Cilium pods to be Ready
      ansible.builtin.command: >
        kubectl wait --for=condition=Ready pods
        -l k8s-app=cilium -n {{ cilium_namespace }} --timeout=300s
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: cilium_wait
      retries: 3
      delay: 20
      until: cilium_wait.rc == 0
      changed_when: false
