---
- name: Install Cilium CNI using Helm
  hosts: localhost
  become: yes
  vars:
    cilium_values_file: "{{ playbook_dir }}/cilium-values.yml"
    cilium_version: "1.17.6"
    cilium_namespace: "kube-system"
    kubeconfig_path: "/etc/kubernetes/admin.conf"

  tasks:
    - name: Ensure Helm repo for Cilium is added
      ansible.builtin.command: helm repo add cilium https://helm.cilium.io
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: helm_repo_add
      changed_when: "'\"cilium\" has been added' in helm_repo_add.stdout or 'already exists' in helm_repo_add.stderr"
      ignore_errors: true

    - name: Update Helm repos
      ansible.builtin.command: helm repo update
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Check if Cilium is already installed
      ansible.builtin.command: helm list -n {{ cilium_namespace }}
      register: helm_list
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    - name: Install Cilium via Helm
      ansible.builtin.command: >
        helm upgrade --install cilium cilium/cilium
        --version {{ cilium_version }}
        --namespace {{ cilium_namespace }}
        --create-namespace
        -f {{ cilium_values_file }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
          #when: "'cilium' not in helm_list.stdout"
      register: cilium_install
      changed_when: "'Release \"cilium\" has been upgraded' in cilium_install.stdout or 'STATUS: deployed' in cilium_install.stdout"
        #ignore_errors: true

    - name: Wait for Cilium pods to be ready
      ansible.builtin.shell: |
        kubectl get pods -n {{ cilium_namespace }} -l k8s-app=cilium \
        -o jsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -q 'false' && exit 1 || exit 0
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      retries: 10
      delay: 15
      register: cilium_readiness
      until: cilium_readiness.rc == 0
      changed_when: false
