- hosts: 152.53.142.69
  become: true
  gather_facts: yes
  roles:
    - role: k8s_cilium_centos
      vars:
        k8s_version: "1.33"
        crio_version: "1.33"
        cilium_cli_version: "v0.18.5"
        cilium_version: "1.17.5"

